# Generated by Django 6.1.1 on 2026-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rescue_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(default='Animal Type', max_length=100)),
                ('condition', models.CharField(default='Condition', max_length=100)),
                ('additional_info', models.TextField(default='Additional Info')),
                ('urgency_level', models.CharField(choices=[('Critical', 'Critical'), ('Urgent', 'Urgent'), ('Non-Urgent', 'Non-Urgent')], default='Medium', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rescue_manager/rescue/')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('contact', models.CharField(default='Contact', max_length=10)),
                ('city', models.CharField(default='City', max_length=100)),
                ('zip_code', models.CharField(default='Zip Code', max_length=10)),
                ('address', models.TextField(default='Address')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
