# Generated by Django 4.2.16 on 2026-09-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue_request',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
