# Generated by Django 6.1.1 on 2026-09-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Content_Manager', 'Content_Manager'), ('Campaign_Manager', 'Campaign_Manager'), ('Rescue_Manager', 'Rescue_Manager'), ('Finance_Manager', 'Finance_Manager'), ('Volunteer_Manager', 'Volunteer_Manager')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('second_contact', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
