# Generated by Django 6.1.1 on 2026-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='managers/profile_pictures/'),
        ),
    ]
