# Generated by Django 6.1.1 on 2026-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_manager_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
