# Generated by Django 6.1.1 on 2026-09-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_manager_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Partner Name', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='content/about/partners/')),
                ('website', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
