from django.urls import path
from . import views

app_name = "public"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("campaigns/", views.campaigns, name="campaigns"),
    path("campaigns/<int:campaign_id>/", views.campaign_detail, name="campaign_detail"),
    path("campaigns/donate/", views.campaign_donate, name="campaign_donate"),
    path("donate/", views.donate, name="donate"),
    path("donate/confirmation/", views.donate_confirmation, name="donate_confirmation"),
    path("events/", views.events, name="events"),
    path("events/<int:event_id>/", views.event_detail, name="event_detail"),
    path("gallery/", views.gallery, name="gallery"),
    path("impact/", views.impact, name="impact"),
    path("login/", views.login, name="login"),
    path("news/", views.news, name="news"),
    path("news/<int:news_id>/", views.news_detail, name="news_detail"),
    path("stories/", views.stories, name="stories"),
    path("stories/<int:story_id>/", views.story_detail, name="story_detail"),
    path("volunteer/", views.volunteer, name="volunteer"),
    path("contact/", views.contact, name="contact"),
    path("faq/", views.faq, name="faq"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("terms/", views.terms, name="terms"),
    path("transparency/", views.transparency, name="transparency"),
    path("adopt/", views.adopt, name="adopt"),
    path("adopt/<int:pk>/", views.adopt_detail, name="adopt_detail"),
    path("adoption-form/", views.adoption_form, name="adoption_form"),
    path("foster/", views.foster, name="foster"),
    path("foster-form/", views.foster_form, name="foster_form"),
    path("report-animal/", views.report_animal, name="report_animal"),
    path("sponsor-animal/", views.sponsor_animal, name="sponsor_animal"),
    path("work/animal-rescue/", views.work_animal_rescue, name="work_animal_rescue"),
    path("work/disaster-relief/", views.work_disaster_relief, name="work_disaster_relief"),
    path("work/environment/", views.work_environment, name="work_environment"),
    path("work/sanitation/", views.work_sanitation, name="work_sanitation"),
    path("dashboard/donor/", views.dashboard_donor, name="dashboard_donor"),
    path("dashboard/rescue-status/", views.dashboard_rescue_status, name="dashboard_rescue_status"),
    path("dashboard/volunteer/", views.dashboard_volunteer, name="dashboard_volunteer"),
    path("sitemap/", views.sitemap, name="sitemap"),
    path("404/", views.page_not_found, name="page_not_found"),
]
