# Generated by Django 4.2.16 on 2026-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('adopt', 'Adopt'), ('donate', 'Donate'), ('rescue', 'Animal Rescue'), ('environment', 'Environment'), ('contact', 'Contact'), ('faq', 'FAQ')], default='home', max_length=20, unique=True),
        ),
    ]
