# Generated by Django 6.1.1 on 2026-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0003_alter_banner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('campaigns', 'Campaigns'), ('stories', 'Stories'), ('volunteer', 'Volunteer'), ('impact', 'Impact'), ('transparency', 'Transparency'), ('privacy_policy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('sitemap', 'Sitemap'), ('adopt', 'Adopt'), ('donate', 'Donate'), ('rescue', 'Animal Rescue'), ('work_animal_rescue', 'Animal Rescue & Healthcare'), ('work_disaster_relief', 'Disaster Relief'), ('work_sanitation', 'Sanitation & Cleanliness'), ('environment', 'Environment'), ('contact', 'Contact'), ('faq', 'FAQ')], default='home', max_length=20, unique=True),
        ),
    ]
