# Generated by Django 6.1.1 on 2026-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0005_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_rescued', models.CharField(default='4,200+', max_length=40)),
                ('animals_treated', models.CharField(default='3,500+', max_length=40)),
                ('trees_planted', models.CharField(default='1,200+', max_length=40)),
                ('cleanups_conducted', models.CharField(default='150+', max_length=40)),
                ('funds_raised', models.CharField(default='2.8Cr', max_length=40)),
                ('active_volunteers', models.CharField(default='840+', max_length=40)),
                ('cities_covered', models.CharField(default='24', max_length=40)),
                ('people_supported', models.CharField(default='1,00,000+', max_length=40)),
            ],
        ),
    ]
