# Generated by Django 6.1.1 on 2026-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0006_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='disaster_ops',
            field=models.CharField(default='47', max_length=40),
        ),
    ]
