# Generated by Django 6.1.1 on 2026-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0007_numbers_disaster_ops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='animals_rescued',
            field=models.IntegerField(default=4200),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='animals_treated',
            field=models.IntegerField(default=3500),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='cleanups_conducted',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='disaster_ops',
            field=models.IntegerField(default=47),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='people_supported',
            field=models.CharField(default='1000+', max_length=40),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='trees_planted',
            field=models.IntegerField(default=1000),
        ),
    ]
