# Generated by Django 6.1.1 on 2026-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0009_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
