# Generated by Django 6.1.1 on 2026-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0010_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.CharField(choices=[('success', 'Success Story'), ('rescue', 'Rescue Story'), ('awareness', 'Awareness Story'), ('campaign', 'Campaign Story'), ('volunteer', 'Volunteer Story'), ('event', 'Event Story'), ('fundraising', 'Fundraising Story'), ('partnership', 'Partnership Story'), ('media', 'Media Story'), ('Disaster Relief', 'Disaster Relief Story'), ('Sanitation', 'Sanitation Story'), ('Environment', 'Environment Story')], default='success', max_length=20),
        ),
    ]
