# Generated by Django 6.1.1 on 2026-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0012_alter_banner_id_alter_homepagecontent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Unke Liye', max_length=200)),
                ('content', models.TextField(default='Unke Liye is a non-profit organization dedicated to rescuing and protecting animals, advocating for communities, and promoting environmental sustainability across India. Our mission is to create a world where every life is valued and cared for.')),
                ('vision_heading', models.CharField(default='Our Vision', max_length=200)),
                ('vision_content', models.TextField(default='To create a compassionate society where animals, communities,and the environment are respected and nurtured.')),
                ('mission_heading', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField(default='To rescue, protect, and advocate for animals, communities, and the environment through direct action, education, and collaboration.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='about_journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2015)),
                ('title', models.CharField(default='Our Journey', max_length=200)),
                ('content', models.TextField(default='From our humble beginnings to our current initiatives, our journey has been one of compassion, dedication, and growth. We have faced challenges and celebrated successes, all while staying true to our mission of making a difference in the lives of those we serve.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='about_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Partner Name', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='content/about/partners/')),
                ('website', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='about_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=200)),
                ('content', models.TextField(default='Unke Liye was founded with the belief that every life deserves care and purpose. Over the years, we have grown into a dedicated team of volunteers and professionals committed to making a positive impact on the lives of animals, communities, and the environment across India.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='about_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('role', models.CharField(default='Founder & CEO', max_length=100)),
                ('bio', models.TextField(default='John Doe is the founder of Unke Liye, with a passion for animal welfare and community development. Under his leadership, the organization has grown to make a significant impact across India.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/about/team/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
