# Generated by Django 6.1.1 on 2026-09-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_managerr', '0013_about_about_journey_about_partners_about_story_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_partners',
        ),
    ]
