# Generated by Django 6.1.1 on 2026-09-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Animal Name', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='adoption/animal/')),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Guinea Pig', 'Guinea Pig'), ('Hamster', 'Hamster'), ('Fish', 'Fish'), ('Reptile', 'Reptile'), ('Amphibian', 'Amphibian'), ('Other', 'Other')], default='other', max_length=100)),
                ('age', models.CharField(default='Age', max_length=100)),
                ('breed', models.CharField(default='Breed', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('medical_notes', models.TextField(default='Medical Notes')),
                ('note', models.TextField(default='Note')),
                ('description', models.TextField(default='Description')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=10)),
                ('weight', models.CharField(default='Weight', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_adopted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='adoption_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(default='Requester Name', max_length=200)),
                ('requester_email', models.EmailField(default='Requester Email', max_length=200)),
                ('requester_contact', models.CharField(default='Requester Contact', max_length=10)),
                ('requester_city', models.CharField(default='Requester City', max_length=100)),
                ('requester_state', models.CharField(default='Requester State', max_length=100)),
                ('requester_zip_code', models.CharField(default='Requester Zip Code', max_length=10)),
                ('requester_address', models.TextField(default='Requester Address')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.animal')),
            ],
        ),
        migrations.CreateModel(
            name='adopted_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_name', models.CharField(default='Adopter Name', max_length=200)),
                ('adopter_email', models.EmailField(default='Adopter Email', max_length=200)),
                ('adopter_contact', models.CharField(default='Adopter Contact', max_length=10)),
                ('adopter_city', models.CharField(default='Adopter City', max_length=100)),
                ('adopter_state', models.CharField(default='Adopter State', max_length=100)),
                ('adopter_zip_code', models.CharField(default='Adopter Zip Code', max_length=10)),
                ('adopters_last_home_visit', models.DateTimeField(blank=True, null=True)),
                ('adopter_address', models.TextField(default='Adopter Address')),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.animal')),
            ],
        ),
        migrations.CreateModel(
            name='animal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('grooming_needs', models.CharField(choices=[('Low maintenance', 'Low maintenance'), ('Medium maintenance', 'Medium maintenance'), ('High maintenance', 'High maintenance')], default='Medium maintenance', max_length=20)),
                ('good_with_dogs', models.BooleanField(default=False)),
                ('good_with_cats', models.BooleanField(default=False)),
                ('good_with_kids', models.BooleanField(default=False)),
                ('rescued_from', models.CharField(default='Rescued From', max_length=200)),
                ('friendly', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.animal')),
            ],
        ),
        migrations.CreateModel(
            name='foster_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(default='Requester Name', max_length=200)),
                ('requester_email', models.EmailField(default='Requester Email', max_length=200)),
                ('requester_contact', models.CharField(default='Requester Contact', max_length=10)),
                ('requester_city', models.CharField(default='Requester City', max_length=100)),
                ('requester_state', models.CharField(default='Requester State', max_length=100)),
                ('requester_zip_code', models.CharField(default='Requester Zip Code', max_length=10)),
                ('requester_address', models.TextField(default='Requester Address')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.animal')),
            ],
        ),
        migrations.CreateModel(
            name='fostered_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foster_name', models.CharField(default='Foster Name', max_length=200)),
                ('foster_email', models.EmailField(default='Foster Email', max_length=200)),
                ('foster_contact', models.CharField(default='Foster Contact', max_length=10)),
                ('foster_city', models.CharField(default='Foster City', max_length=100)),
                ('foster_state', models.CharField(default='Foster State', max_length=100)),
                ('foster_zip_code', models.CharField(default='Foster Zip Code', max_length=10)),
                ('foster_address', models.TextField(default='Foster Address')),
                ('fostering_start_date', models.DateTimeField(auto_now_add=True)),
                ('fostering_end_date', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.animal')),
            ],
        ),
    ]
