# Generated by Django 6.1.1 on 2026-09-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='available_for_adoption',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='sponsored_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approx_expenses', models.IntegerField(default=1000)),
                ('current_fund', models.IntegerField(default=0)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_renewal', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('One-time', 'One-time')], default='Monthly', max_length=20)),
                ('donation_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.animal')),
            ],
        ),
    ]
