# Generated by Django 6.1.1 on 2026-09-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dept', '0002_animal_available_for_adoption_sponsored_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored_animal',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='sponsored_animal',
            name='donation_renewal',
        ),
        migrations.RemoveField(
            model_name='sponsored_animal',
            name='donation_renewal_date',
        ),
        migrations.CreateModel(
            name='sponser_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sponser Name', max_length=200)),
                ('email', models.EmailField(default='Sponser Email', max_length=200)),
                ('contact', models.CharField(default='Sponser Contact', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_renewal', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('One-time', 'One-time')], default='Monthly', max_length=20)),
                ('donation_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption_dept.sponsored_animal')),
            ],
        ),
    ]
