# Generated by Django 6.1.1 on 2026-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dept', '0003_remove_sponsored_animal_donation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='available_for_adoption',
        ),
        migrations.AddField(
            model_name='animal_details',
            name='available_for_adoption',
            field=models.BooleanField(default=True),
        ),
    ]
