# Generated by Django 6.1.1 on 2026-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dept', '0004_remove_animal_available_for_adoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_details',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal_details',
            name='neutering_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal_details',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal_details',
            name='vaccination_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
