# Generated by Django 6.1.1 on 2026-09-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dept', '0005_animal_details_neutered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_details',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Foster First', 'Foster First'), ('Senior', 'Senior')], default='Available', max_length=20),
        ),
    ]
